# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'DataLayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxAlamofire'
  pod 'RxSwift'
  # Pods for Data

end

target 'Domain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'

  # Pods for Domain

end

target 'limonadier' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for Limonadier
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'limonadierTests' do
  # Pods for testing
  pod 'RxSwift'
  pod 'RxCocoa'
end


